# SPDX-License-Identifier GPL-2.0+
---
# Our sensible defaults for the nfsd role.
nfsd_lvm_pvs: []
nfsd_export_device_prefix: ""
nfsd_export_device_count: 0
nfsd_export_label: "export"
nfsd_export_fs_opts: ""
nfsd_lease_time: "90"
