---
- name: Debian-specific setup
  ansible.builtin.include_tasks: roles/nfsd/tasks/install-deps/debian/main.yml
  when: ansible_os_family == 'Debian'

- name: SuSE-specific setup
  ansible.builtin.include_tasks: roles/nfsd/tasks/install-deps/suse/main.yml
  when: ansible_os_family == 'Suse'

- name: Red Hat-specific setup
  ansible.builtin.include_tasks: roles/nfsd/tasks/install-deps/redhat/main.yml
  when: ansible_os_family == 'RedHat'

- name: Generate /etc/nfs.conf
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  template:
    src: nfs.conf.j2
    dest: /etc/nfs.conf
    owner: root
    group: root
    mode: 0644

- name: Build string of devices to use as PVs
  set_fact:
    nfsd_lvm_pvs: "{{ nfsd_lvm_pvs + [ nfsd_export_device_prefix + item|string ] }}"
  with_items: "{{ range(1, nfsd_export_device_count + 1) }}"

- name: Print the PV list
  ansible.builtin.debug:
    var: nfsd_lvm_pvs

- name: Create a new LVM VG
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  community.general.lvg:
    vg: "exports"
    pvs: "{{ nfsd_lvm_pvs | join(',') }}"

- name: Create {{ nfsd_export_path }}
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  ansible.builtin.file:
    path: "{{ nfsd_export_path }}"
    state: directory
    mode: 0755

- name: Test whether SELinux is enabled
  command: /usr/sbin/selinuxenabled
  register: selinux_status
  changed_when: False
  failed_when: False

- name: Copy SELinux type enforcement file to server
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  copy:
    src: "{{ playbook_dir }}/roles/nfsd/templates/nfsd_policy.te"
    dest: "/root/nfsd_policy.te"
    owner: root
    group: root
    mode: 0644
  when: selinux_status.rc == 0

- name: Convert SELinux type enforcement file to a policy module
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: /usr/bin/checkmodule -M -m -o /root/nfsd_policy.mod /root/nfsd_policy.te
  when: selinux_status.rc == 0

- name: Compile SELinux policy module into policy package
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: /usr/bin/semodule_package -o /root/nfsd_policy.pp -m /root/nfsd_policy.mod
  when: selinux_status.rc == 0

- name: Install SELinux policy module
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: /usr/sbin/semodule -i /root/nfsd_policy.pp
  when: selinux_status.rc == 0

- name: Allow nfsd full access to {{ nfsd_export_path }}
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  community.general.sefcontext:
    target: "{{ nfsd_export_path }}(/.*)?"
    setype: public_content_rw_t
    state: present
  when: selinux_status.rc == 0

# FIXME: open ports instead
- name: Populate service facts
  service_facts:

- name: Turn off firewalld
  become: yes
  ansible.builtin.systemd_service:
    name: firewalld.service
    enabled: false
    state: stopped
  when: '"firewalld.service" in ansible_facts.services'

- name: Start up nfsd
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  ansible.builtin.systemd_service:
    name: nfs-server.service
    enabled: true
    state: reloaded
