---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

- name: Import optional distribution specific variables
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "{{ ansible_facts['os_family']|lower }}.yml"
      skip: true
  tags: vars

# vagrant has no single command line to check for this so we have to
# wrap it up ourselves, and we only add a box if not present
- name: Add cloud image box if not present
  shell: |
    set -o pipefail
    {{ role_path }}/scripts/add-box-if-missing.sh {{ item.name }} {{ item.box_url }}
  args:
    executable: /bin/bash
    chdir: "{{ role_path }}"
  register: box_check
  changed_when: box_check.rc == 314
  failed_when: ( box_check.rc not in [ 0,  314, 58 ] )
  # with_items:
  #   - "{{ vagrant_boxes }}"
  loop_control:
    label: "Adding cloud image box {{ item.name }} if not present"
  tags: [ 'kubernetes', 'box', 'install' ]
  when:
    - kdevops_install_vagrant_boxes|bool
